Feature/image capture overlay
uwcirg/tb-mobile-app pull request #466
Opened 2022-09-13 20:53 UTC by johnny2smooth

Sorry for the length of the PR! I thought that these featured kinda chunked together but i think the scope eventually got a little too large. 

Still needs notifications set up when a patient has not waited 20 minutes. That can be fixed/featured in another branch though!

2022-09-24 14:08 UTC, kylegoodwin requested changes
Overall looks good. Left some UI notes that shouldn't take long to fix. Also there are some missing translations.

2022-09-24 14:08 UTC, kylegoodwin commented on src/Patient/ReportingFlows/TimeoutPrompts.js
> +    console.log(min);
take out this console.log

2022-09-24 14:08 UTC, kylegoodwin commented on src/Patient/ReportingFlows/TimeoutPrompts.js
> +            ? 'I have waited for twenty minutes'
Translations

2022-09-24 14:08 UTC, kylegoodwin commented on src/Patient/ReportingFlows/TimeoutPrompts.js
> +        icon={valid ? <ThumbUp /> : <Timer />}
If you are using new colors here, just thow them in the Colors file to keep track of them

2022-09-24 14:08 UTC, kylegoodwin commented on src/ImageCapture/ImageOverlay.js
> +      <img
<img width="386" alt="Screen Shot 2022-09-24 at 9 58 32 AM" src="https://user-images.githubusercontent.com/10137989/192102252-36391ed6-88cb-45a0-96c2-d5d6eae6bdf1.png">

Also noticed it breaks in offline mode.

Not a big deal, but maybe just hide this if offline. There is an easy way to check offline with mobx.
I think its uiStore.offline ?, just search its used all over the place.

We could also pre-cache the image if you want

2022-09-27 15:04 UTC, johnny2smooth commented on src/ImageCapture/ImageOverlay.js
> +      <img
I'll hide it for now, but I'm interested in caching. I haven't done that yet

2022-09-27 15:35 UTC, johnny2smooth commented on src/ImageCapture/ImageOverlay.js
> +      <img
Yea i think that caching would be best because Camera is a class component and I can't use hooks in there

2022-09-27 15:50 UTC, kylegoodwin commented on src/ImageCapture/ImageOverlay.js
> +      <img
@johnny2smooth the "ImageOverlay" component is seperate, so you can just use a hook in there and render nothing if its offline

2022-09-27 15:51 UTC, kylegoodwin commented on src/ImageCapture/ImageOverlay.js
> +      <img
If you are curious though, this is where I am caching the main logo 

https://github.com/uwcirg/tb-mobile-app/blob/894525f5141741108eb28b5d2238d96de5619804/public/custom-service-worker.js#L23

2022-09-27 17:00 UTC, johnny2smooth commented on src/ImageCapture/ImageOverlay.js
> +      <img
Ahhh yes good call!!

2022-09-28 21:54 UTC, merged